// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbiC5_ZI3lUOqW2LRQe8z1R0ALii2LPDc',
    appId: '1:955695034749:web:dd3b8678e9a224e7e55c14',
    messagingSenderId: '955695034749',
    projectId: 'shop-28472',
    authDomain: 'shop-28472.firebaseapp.com',
    storageBucket: 'shop-28472.appspot.com',
    measurementId: 'G-P8J12KBV5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25ANGlVR8Ogr-RhQ1oJ1Uh69JmiienXA',
    appId: '1:955695034749:android:8784be002fb9b69ce55c14',
    messagingSenderId: '955695034749',
    projectId: 'shop-28472',
    storageBucket: 'shop-28472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC4jK9354lgPHQD_r8-hRaLwYc7RmUpyk',
    appId: '1:955695034749:ios:b4a08e40d7a7a620e55c14',
    messagingSenderId: '955695034749',
    projectId: 'shop-28472',
    storageBucket: 'shop-28472.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbiC5_ZI3lUOqW2LRQe8z1R0ALii2LPDc',
    appId: '1:955695034749:web:811678f5aceac0a0e55c14',
    messagingSenderId: '955695034749',
    projectId: 'shop-28472',
    authDomain: 'shop-28472.firebaseapp.com',
    storageBucket: 'shop-28472.appspot.com',
    measurementId: 'G-ZELM7JMGNJ',
  );
}
